<!-- Thumbnails -->
<div class="twelve columns">
	<h1><?= $this->title ?></h1>
</div>

<div class="twelve columns">
	<ul class="block-grid three-up">
		<?php $i = 0; foreach($this->images as $image): ?>

		<?php $size = $image->getSize(); ?>

		<li>
			<div class="panel">
			<img src="../../public/images/uploaded/<?= $image->getFilename() ?>" <?= $size[3] ?>>

				<h5><?= $image->getTitle() ?></h5>
				<h6 class="subheader"><?= $image->getDescription() ?></h6>
				<p class="attributes">
					<strong>Rating</strong>: <span class="rating-label"><?= $image->getRating() ?></span>
					<button class="tiny button vote-up" data-image="<?= $image->getFilename() ?>">Vote Up</button>
					<button class="tiny button vote-down" data-image="<?= $image->getFilename() ?>">Vote Down</button>
					<br>
					<strong>Date</strong>: <?= @date('j M Y H:i', $image->getDate()) ?>
				</p>
			</div>
		</li>

		<?php $i++; endforeach; ?>

<!-- End Thumbnails -->

	</ul>
</div>
