<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />

	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width" />

	<title>Image Rating</title>
	
	<!-- Included CSS Files (Compressed) -->
	<link rel="stylesheet" href="../../public/css/foundation.min.css">
	<link rel="stylesheet" href="../../public/css/app.css">

	<script src="../../public/js/modernizr.foundation.js"></script>
</head>
<body>

	<div class="row">
		<div class="twelve columns">

		<!-- Navigation -->

			<div class="row">
				<div class="twelve columns">

					<ul class="top-bar">

						<ul>
					<li class="name"><h1><a href="../home/">Image Rater</a></h1></li>
					<li class="toggle-topbar"><a href="#"></a></li>
				</ul>

				<section>
					<ul class="left">
						<li><a href="../popular/">Popular</a></li>
						<li><a href="../recent/">Recent</a></li>
					</ul>

					<ul class="right">
						<li><a href="../upload/">Upload Image</a></li>
						<?php if (isset($_SESSION['loggedin'])): ?>
						<li><a href="../logout/">Logout</a></li>
						<?php endif; ?>
					</ul>
				</section>

			</div>
		</div>

		<!-- End Navigation -->

		<div class="row">
			<?= $this->content ?>
		</div>


		<!-- Footer -->

			<footer class="row">
				<div class="twelve columns"><hr />
					<div class="row">

						<div class="twelve columns">
							<p>&copy; Trevor Dixon</p>
						</div>

					</div>
				</div>
			</footer>

		<!-- End Footer -->

		</div>
	</div>	
	<!-- Included JS Files (Compressed) -->
	<script src="../../public/js/foundation.min.js"></script>
	<?php
		if (is_array($this->scripts)) {
			foreach ($this->scripts as $script) {
				echo $script . "\n";
			}
		}
	?>

	<!-- Initialize JS Plugins -->
	<script src="../../public/js/app.js"></script>
</body>
</html>
