<div class="twelve columns">
	<h1>Login</h1>
	<h5 class="subheader">Username <strong>admin</strong>, password <strong>password</strong>.</h5>
</div>

<form method="post">

<?php if ($this->error): ?>
		<div class="twelve columns error">
			<label class="error"><?= $this->error ?></label>
		</div>
<?php endif; ?>

	<div class="row">
		<div class="two columns">
			<label class="right inline">Username:</label>
		</div>
		<div class="ten columns">
			<input type="text" class="three" value="admin" name="user">
		</div>
	</div>
	<div class="row">
		<div class="two columns">
			<label class="right inline">Password:</label>
		</div>
		<div class="ten columns">
			<input type="password" class="three" value="password" name="password">
		</div>
	</div>

	<div class="row">
		<button class="offset-by-two button" type="submit">Login</button>
	</div>
</form>